.\" OpenBSD-style concise man page for false
.Dd $Mdocdate$
.Dt FALSE 1
.Os
.Sh NAME
.Nm false
.Nd do nothing, unsuccessfully
.Sh SYNOPSIS
.Nm false
.Op Ar ignored_arguments ...
.Sh DESCRIPTION
The
.Nm
utility does nothing and returns an exit status of 1 to indicate failure.
All arguments are ignored.
.Pp
The
.Nm
utility is useful in shell scripts and command line constructs where
a command that always fails is needed, such as in loops or conditional
statements.
.Sh EXIT STATUS
.Ex -std false
.Pp
The
.Nm
utility always exits with status 1.
.Sh EXAMPLES
Use in a conditional statement:
.Bd -literal -offset indent
$ if false; then echo "This will not print"; fi
.Ed
.Pp
Use in a loop that should not execute:
.Bd -literal -offset indent
$ while false; do echo "This will not print"; done
.Ed
.Pp
Demonstrate that all arguments are ignored:
.Bd -literal -offset indent
$ false --help --version any arguments
$ echo $?
1
.Ed
.Sh SEE ALSO
.Xr test 1 ,
.Xr true 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
IEEE Std 1003.1-2024 ("POSIX.1")
specification.
.Sh AUTHORS
.An "vibeutils implementation by Travis Cole"