.Dd July 26, 2025
.Dt MKDIR 1
.Os
.Sh NAME
.Nm mkdir
.Nd make directories
.Sh SYNOPSIS
.Nm mkdir
.Op Fl pv
.Op Fl m Ar mode
.Ar directory ...
.Sh DESCRIPTION
The
.Nm
utility creates the directories named as operands, in the order specified,
using mode
.Li rwxrwxrwx
(0777) as modified by the current
.Xr umask 2 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl m Ar mode
Set the file permission bits of the final created directory to
the specified mode.
The mode argument can be in any of the formats specified to the
.Xr chmod 1
command.
If a symbolic mode is specified, the operation characters
.Dq +
and
.Dq -
are interpreted relative to an initial mode of
.Dq a=rwx .
.It Fl p , Fl Fl parents
Create intermediate directories as required.
If this option is not specified, the full path prefix of each
operand must already exist.
On the other hand, with this option specified, no error will be
reported if a directory given as an operand already exists.
Intermediate directories are created with permission bits of
.Li rwxrwxrwx
(0777) as modified by the current umask, plus write and search
permission for the owner.
.It Fl v , Fl Fl verbose
Be verbose when creating directories, listing them as they are created.
.It Fl h , Fl Fl help
Display help message and exit.
.It Fl V , Fl Fl version
Display version information and exit.
.El
.Pp
The user must have write permission in the parent directory.
.Sh EXIT STATUS
.Ex -std mkdir
.Sh EXAMPLES
Create a simple directory:
.Bd -literal -offset indent
$ mkdir newdir
.Ed
.Pp
Create nested directories with parent creation:
.Bd -literal -offset indent
$ mkdir -p project/src/main
.Ed
.Pp
Create directory with specific permissions:
.Bd -literal -offset indent
$ mkdir -m 755 public_dir
.Ed
.Sh SEE ALSO
.Xr chmod 1 ,
.Xr rmdir 1 ,
.Xr umask 2
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2017
specification.
.Pp
The
.Fl v
option is an extension to that specification.
.Sh AUTHORS
.An "vibeutils implementation by Travis Cole"