.\" OpenBSD-style concise man page
.Dd $Mdocdate$
.Dt RMDIR 1
.Os
.Sh NAME
.Nm rmdir
.Nd remove empty directories
.Sh SYNOPSIS
.Nm
.Op Fl pv
.Op Fl Fl ignore-fail-on-non-empty
.Ar directory ...
.Sh DESCRIPTION
The
.Nm
utility removes the directory entry specified by each
.Ar directory
argument, provided it is empty.
When standard error is a terminal, a not-empty diagnostic
may append a suggestion to use
.Nm rm Fl r .
.Pp
Arguments are processed in the order given.
To remove both a parent directory and a subdirectory
of that parent, the subdirectory
must be specified first so the parent directory
is empty when
.Nm
tries to remove it.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h , Fl Fl help
Display help and exit.
.It Fl p , Fl Fl parents
Remove
.Ar directory
and its ancestors.
For example,
.Ql rmdir -p a/b/c
is similar to
.Ql rmdir a/b/c a/b a .
Directories are removed from leaf to root.
If any removal fails, processing stops.
.It Fl v , Fl Fl verbose
Print each directory as it is removed.
.It Fl V , Fl Fl version
Output version information and exit.
.It Fl Fl ignore-fail-on-non-empty
Ignore failures caused by non-empty directories.
.El
.Sh EXIT STATUS
.Ex -std rmdir
.Sh EXAMPLES
Remove an empty directory:
.Bd -literal -offset indent
$ rmdir foobar
.Ed
.Pp
Remove a directory tree from leaf to root:
.Bd -literal -offset indent
$ rmdir -p cow/horse/monkey
.Ed
.Pp
Remove directories, ignoring non-empty ones:
.Bd -literal -offset indent
$ rmdir --ignore-fail-on-non-empty -p project/build/temp
.Ed
.Sh SEE ALSO
.Xr mkdir 1 ,
.Xr rm 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
.Sh AUTHORS
.An "vibeutils implementation by Travis Cole"
